# Generated by Django 5.0.1 on 2024-01-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='currency',
        ),
    ]
